const constants = {
    CHOOSE_PRODUCT: 'CHOOSE_PRODUCT',
    END: 'END',
    ENTER_INPUT_1: 'ENTER_INPUT_1',
    ENTER_INPUT_2: 'ENTER_INPUT_2',
    INSERT_MONEY : 'INSERT_MONEY',
    PRODUCT_WAS_SELECTED: 'PRODUCT_WAS_SELECTED',
    RESET:'RESET',
    RESTORE_DEFAULT_VALUE: 'RESTORE_DEFAULT_VALUE',
    TAKE_PURCHASE: 'TAKE_PURCHASE',
};
 export default constants;